--
-- PostgreSQL database dump
--

\restrict pZPtqduYDsekI8n97Ypo3HBltnekcqQUBVRaXs6dsl4woB0q2MgxGrstKxp2ur1

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;



CREATE TABLE public.learning_insights (
    user_id bigint NOT NULL,
    display_name text NOT NULL,
    learning_styles_cluster_label text,
    learning_styles_insight text,
    learning_styles_suggestion text,
    exam_submission_cluster_label text,
    exam_submission_insight text,
    exam_submission_suggestion text,
    created_at timestamp without time zone DEFAULT now(),
    source text DEFAULT 'ml'::text NOT NULL,
    CONSTRAINT learning_insights_source_check CHECK ((source = ANY (ARRAY['ml'::text, 'manual'::text])))
);


ALTER TABLE public.learning_insights OWNER TO postgres;



COPY public.learning_insights (user_id, display_name, learning_styles_cluster_label, learning_styles_insight, learning_styles_suggestion, exam_submission_cluster_label, exam_submission_insight, exam_submission_suggestion, created_at, source) FROM stdin;
3390	istiabudi73	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.54 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 79.83 dengan tingkat kelulusan 72.3%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
5774	budhisant	At-Risk Learners	Anda adalah seorang At-Risk Learner. Pola belajar Anda menunjukkan tantangan yang perlu perhatian khusus.	Mulai dengan menetapkan target mingguan yang realistis. Konsistensi lebih penting daripada kecepatan. Pertimbangkan untuk membuat jadwal belajar yang lebih terstruktur dan minta bantuan ketika dibutuhkan.	Needs Improvement	Rata-rata nilai ujian Anda adalah 67.09 dengan tingkat kelulusan 52.1%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
11836	diinggo	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.29 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 79.50 dengan tingkat kelulusan 77.7%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
17833	fahram	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.08 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 86.27 dan tingkat kelulusan 84.4%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
32258	muftialies	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.50 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 84.59 dengan tingkat kelulusan 81.6%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
96989	igihcksn	At-Risk Learners	Anda adalah seorang At-Risk Learner. Pola belajar Anda menunjukkan tantangan yang perlu perhatian khusus.	Mulai dengan menetapkan target mingguan yang realistis. Konsistensi lebih penting daripada kecepatan. Pertimbangkan untuk membuat jadwal belajar yang lebih terstruktur dan minta bantuan ketika dibutuhkan.	Needs Improvement	Rata-rata nilai ujian Anda adalah 71.46 dengan tingkat kelulusan 59.8%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
102556	fakhry	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.89 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 84.43 dengan tingkat kelulusan 80.7%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
110119	jokoss92	At-Risk Learners	Anda adalah seorang At-Risk Learner. Pola belajar Anda menunjukkan tantangan yang perlu perhatian khusus.	Mulai dengan menetapkan target mingguan yang realistis. Konsistensi lebih penting daripada kecepatan. Pertimbangkan untuk membuat jadwal belajar yang lebih terstruktur dan minta bantuan ketika dibutuhkan.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 84.85 dengan tingkat kelulusan 85.0%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
113842	Saad_Fauzi	At-Risk Learners	Anda adalah seorang At-Risk Learner. Pola belajar Anda menunjukkan tantangan yang perlu perhatian khusus.	Mulai dengan menetapkan target mingguan yang realistis. Konsistensi lebih penting daripada kecepatan. Pertimbangkan untuk membuat jadwal belajar yang lebih terstruktur dan minta bantuan ketika dibutuhkan.	Needs Improvement	Rata-rata nilai ujian Anda adalah 73.44 dengan tingkat kelulusan 60.5%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
153116	silmiathqia	At-Risk Learners	Anda adalah seorang At-Risk Learner. Pola belajar Anda menunjukkan tantangan yang perlu perhatian khusus.	Mulai dengan menetapkan target mingguan yang realistis. Konsistensi lebih penting daripada kecepatan. Pertimbangkan untuk membuat jadwal belajar yang lebih terstruktur dan minta bantuan ketika dibutuhkan.	Needs Improvement	Rata-rata nilai ujian Anda adalah 66.80 dengan tingkat kelulusan 53.8%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
433737	suryani-lestari	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 2.98 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Kecepatan Anda bagus, tapi pastikan pemahaman yang mendalam. Dedikasikan lebih banyak waktu untuk pendalaman materi dan latihan soal.	Needs Improvement	Rata-rata nilai ujian Anda adalah 64.67 dengan tingkat kelulusan 53.9%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
494342	andiirhamm	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.28 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 76.11 dengan tingkat kelulusan 68.5%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
496740	fauzulhanif16	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 3.15 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 78.57 dengan tingkat kelulusan 72.9%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
518124	anddfian	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 0.95 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 90.57 dan tingkat kelulusan 91.4%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
531259	wilson_oey	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 3.04 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Kecepatan Anda bagus, tapi pastikan pemahaman yang mendalam. Dedikasikan lebih banyak waktu untuk pendalaman materi dan latihan soal.	Needs Improvement	Rata-rata nilai ujian Anda adalah 67.63 dengan tingkat kelulusan 56.7%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
791882	bagusangkasawan	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 2.20 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 81.42 dengan tingkat kelulusan 78.1%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
886996	akhsaul	Steady Learners	Anda adalah seorang Steady Learner! Anda menunjukkan pola belajar yang stabil dan konsisten dengan kecepatan 1.32 modul per hari.	Pola belajar Anda yang konsisten terbukti efektif! Pertahankan momentum ini dan pertimbangkan untuk meningkatkan kecepatan belajar secara bertahap.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 80.75 dengan tingkat kelulusan 75.2%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
938276	nurrizkiadip	At-Risk Learners	Anda adalah seorang At-Risk Learner. Pola belajar Anda menunjukkan tantangan yang perlu perhatian khusus.	Mulai dengan menetapkan target mingguan yang realistis. Konsistensi lebih penting daripada kecepatan. Pertimbangkan untuk membuat jadwal belajar yang lebih terstruktur dan minta bantuan ketika dibutuhkan.	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 84.49 dengan tingkat kelulusan 85.4%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
1202367	muhhanif99	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 2.85 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Kecepatan Anda bagus, tapi pastikan pemahaman yang mendalam. Dedikasikan lebih banyak waktu untuk pendalaman materi dan latihan soal.	Needs Improvement	Rata-rata nilai ujian Anda adalah 57.26 dengan tingkat kelulusan 37.6%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
1319457	mawann	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 2.52 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 95.07 dan tingkat kelulusan 96.2%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
1776122	aslich	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 1.69 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 82.09 dengan tingkat kelulusan 82.1%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
2131303	rezaikbal	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 4.06 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 81.56 dengan tingkat kelulusan 79.5%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
2135328	andrewbj	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 2.90 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 90.66 dan tingkat kelulusan 90.9%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
2395575	ykbintang	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 2.58 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 89.08 dan tingkat kelulusan 91.2%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
3557828	nielshn11	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 4.43 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 87.79 dan tingkat kelulusan 92.0%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
5021477	rifath_2SXp	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 7.44 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Good Performers	Anda adalah seorang Good Performer. Rata-rata nilai ujian Anda adalah 85.05 dengan tingkat kelulusan 85.7%.	Anda sudah berada di jalur yang benar! Fokus pada area yang masih perlu ditingkatkan, seperti memperdalam pemahaman materi dan meningkatkan kualitas tugas.	2025-12-12 00:32:11.961276	ml
5044844	ledis_idola_h8Ge	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 9.73 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Luar biasa! Pertahankan momentum Anda dan coba tantangan level yang lebih tinggi untuk pengembangan karir!	Excellent Performers	Anda adalah seorang Excellent Performer! Dengan rata-rata nilai ujian 91.57 dan tingkat kelulusan 97.2%, Anda menunjukkan performa yang luar biasa.	Pertahankan prestasi Anda dan terus tantang diri Anda dengan materi yang lebih kompleks untuk pengembangan karir!	2025-12-12 00:32:11.961276	ml
5051374	fkaslana	Fast & Consistent Learners	Anda adalah seorang Fast & Consistent Learner! Dengan kecepatan 1.72 modul per hari, Anda menunjukkan pembelajaran yang cepat dan teratur.	Kecepatan Anda bagus, tapi pastikan pemahaman yang mendalam. Dedikasikan lebih banyak waktu untuk pendalaman materi dan latihan soal.	Needs Improvement	Rata-rata nilai ujian Anda adalah 68.10 dengan tingkat kelulusan 60.0%.	Jangan berkecil hati! Identifikasi area yang perlu ditingkatkan, manfaatkan sumber belajar tambahan, dan pertimbangkan untuk berdiskusi dengan mentor atau rekan belajar.	2025-12-12 00:32:11.961276	ml
\.




ALTER TABLE ONLY public.learning_insights
    ADD CONSTRAINT learning_insights_pkey PRIMARY KEY (user_id);




\unrestrict pZPtqduYDsekI8n97Ypo3HBltnekcqQUBVRaXs6dsl4woB0q2MgxGrstKxp2ur1

