import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { deleteManualInsight, listInsights } from "../api/insightsApi";

function InsightRow({ row, rightActions }) {
  return (
    <div
      className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white/90 p-3 shadow-sm
                 dark:border-slate-800 dark:bg-slate-900/90 sm:flex-row sm:items-start sm:justify-between"
    >
      <div className="min-w-0">
        <p className="text-[11px] font-semibold text-slate-900 dark:text-slate-50">
          <span className="break-words">{row.display_name}</span>{" "}
          <span className="text-slate-400">•</span> ID:{" "}
          <span className="break-words">{row.user_id}</span>
        </p>

        <p className="mt-1 text-[11px] text-slate-600 dark:text-slate-400">
          <span className="break-words">
            {row.learning_styles_cluster_label || "-"}
          </span>{" "}
          <span className="text-slate-400">|</span>{" "}
          <span className="break-words">
            {row.exam_submission_cluster_label || "-"}
          </span>
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-2 sm:justify-end">
        {rightActions}
      </div>
    </div>
  );
}

export default function AdminDashboard() {
  const navigate = useNavigate();

  const [ml, setMl] = useState([]);
  const [manual, setManual] = useState([]);

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const [busyId, setBusyId] = useState(null);

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      const [mlRows, manualRows] = await Promise.all([
        listInsights("ml"),
        listInsights("manual"),
      ]);
      setMl(mlRows);
      setManual(manualRows);
    } catch (e) {
      setError(e.message || "Gagal memuat admin dashboard.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const handleDelete = async (userId) => {
    const ok = window.confirm(`Hapus insight manual untuk user_id=${userId}?`);
    if (!ok) return;

    setBusyId(userId);
    try {
      await deleteManualInsight(userId);
      await load();
    } catch (e) {
      alert(e.message || "Gagal delete.");
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div className="mx-auto mt-4 max-w-5xl space-y-4 px-4 sm:px-6 lg:px-8 pb-8">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <button
          type="button"
          onClick={() => navigate("/")}
          className="inline-flex w-full items-center justify-center gap-1 rounded-full border border-slate-300 bg-white/80 px-3 py-1 text-[11px] font-medium text-slate-700 shadow-sm
                     hover:bg-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800 sm:w-auto"
        >
          <span aria-hidden="true">←</span>
          Back to Home
        </button>

        <button
          type="button"
          onClick={load}
          className="inline-flex w-full items-center justify-center gap-1 rounded-full bg-sky-600 px-3 py-1.5 text-[11px] font-medium text-white shadow-sm hover:bg-sky-500 sm:w-auto"
        >
          ↻ Refresh
        </button>
      </div>

      <div>
        <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">
          Admin Dashboard
        </p>
        <h1 className="mt-1 text-xl font-semibold text-slate-900 dark:text-slate-50">
          Insights Overview
        </h1>
      </div>

      {loading && (
        <div className="rounded-2xl border border-slate-200 bg-white/80 p-4 text-sm text-slate-600 dark:border-slate-800 dark:bg-slate-900/80 dark:text-slate-300">
          Memuat data...
        </div>
      )}

      {!loading && error && (
        <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-700/60 dark:bg-red-900/40 dark:text-red-100">
          {error}
        </div>
      )}

      {!loading && !error && (
        <div className="grid gap-4 lg:grid-cols-2">
          {/* ML LIST */}
          <section className="space-y-3">
            <div className="flex items-center justify-between gap-2">
              <h2 className="min-w-0 text-sm font-semibold text-slate-900 dark:text-slate-50">
                Generated by Machine Learning Model
              </h2>
              <span className="shrink-0 text-[10px] text-slate-400 dark:text-slate-500">
                {ml.length} items
              </span>
            </div>

            <div className="space-y-2">
              {ml.map((row) => (
                <InsightRow
                  key={row.user_id}
                  row={row}
                  rightActions={
                    <button
                      type="button"
                      onClick={() => navigate(`/insight/${row.user_id}`)}
                      className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-[11px] font-medium text-slate-700 hover:bg-slate-100
                                 dark:border-slate-700 dark:bg-slate-950/60 dark:text-slate-200 dark:hover:bg-slate-950"
                    >
                      View
                    </button>
                  }
                />
              ))}

              {ml.length === 0 && (
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Tidak ada data ML.
                </p>
              )}
            </div>
          </section>

          {/* MANUAL LIST */}
          <section className="space-y-3">
            <div className="flex items-center justify-between gap-2">
              <h2 className="min-w-0 text-sm font-semibold text-slate-900 dark:text-slate-50">
                Added Manually by User
              </h2>
              <span className="shrink-0 text-[10px] text-slate-400 dark:text-slate-500">
                {manual.length} items
              </span>
            </div>

            <div className="space-y-2">
              {manual.map((row) => (
                <InsightRow
                  key={row.user_id}
                  row={row}
                  rightActions={
                    <>
                      <button
                        type="button"
                        onClick={() => navigate(`/edit/${row.user_id}`)}
                        className="rounded-full bg-emerald-600 px-3 py-1 text-[11px] font-medium text-white shadow-sm hover:bg-emerald-500"
                      >
                        Update
                      </button>

                      <button
                        type="button"
                        onClick={() => handleDelete(row.user_id)}
                        disabled={busyId === row.user_id}
                        className="rounded-full bg-rose-600 px-3 py-1 text-[11px] font-medium text-white shadow-sm hover:bg-rose-500 disabled:opacity-70"
                      >
                        {busyId === row.user_id ? "..." : "Delete"}
                      </button>

                      <button
                        type="button"
                        onClick={() => navigate(`/insight/${row.user_id}`)}
                        className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-[11px] font-medium text-slate-700 hover:bg-slate-100
                                   dark:border-slate-700 dark:bg-slate-950/60 dark:text-slate-200 dark:hover:bg-slate-950"
                      >
                        View
                      </button>
                    </>
                  }
                />
              ))}

              {manual.length === 0 && (
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Tidak ada data manual.
                </p>
              )}
            </div>

            <button
              type="button"
              onClick={() => navigate("/add")}
              className="mt-2 inline-flex w-full items-center justify-center gap-1 rounded-full bg-sky-600 px-3 py-2 text-[11px] font-medium text-white shadow-sm hover:bg-sky-500 sm:w-auto sm:py-1.5"
            >
              + Add New Insight
            </button>
          </section>
        </div>
      )}
    </div>
  );
}
